# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

def shared_pods
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'self-embedded-ios', :git => 'https://github.com/joinself/self-embedded-ios.git'
  
  pod 'MBProgressHUD'
  
  pod 'SwiftyBeaver'
end

target 'ExampleA' do
  shared_pods
end

target 'ExampleB' do
  shared_pods
end

target 'SelfAppDemo' do
  shared_pods
end

target 'SwiftUIHostApp' do
  shared_pods
end

post_install do |installer|
installer.pods_project.build_configurations.each do |config|
  #config.build_settings['VALID_ARCHS'] = 'arm64, arm64e, x86_64'
  config.build_settings["EXCLUDED_ARCHS"] = "armv7"
end

installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = "13.0"
  end
end

installer.pods_project.targets.each do |target|
  if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
    target.build_configurations.each do |config|
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
    end
  end
end
end

